apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics-config
  namespace: kafka
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      # Kafka broker metrics
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          broker: "$4:$5"
      - pattern: kafka.server<type=(.+), name=(.+)><>OneMinuteRate
        name: kafka_server_$1_$2_oneminuterate
        type: GAUGE
      - pattern: kafka.server<type=(.+), name=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
      # Kafka controller metrics
      - pattern: kafka.controller<type=(.+), name=(.+)><>Value
        name: kafka_controller_$1_$2
        type: GAUGE
      # Kafka network metrics
      - pattern: kafka.network<type=(.+), name=(.+)><>Value
        name: kafka_network_$1_$2
        type: GAUGE
      # Kafka log metrics
      - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
        name: kafka_log_$1_$2
        type: GAUGE
        labels:
          topic: "$3"
          partition: "$4"
      # JVM metrics
      - pattern: java.lang<type=OperatingSystem><>ProcessCpuLoad
        name: jvm_process_cpu_load
        type: GAUGE
      - pattern: java.lang<type=Memory><HeapMemoryUsage>(\w+)
        name: jvm_heap_memory_$1_bytes
        type: GAUGE
  kafka-connect-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: kafka.connect<type=(.+), connector=(.+), task=(.+)><>Value
        name: kafka_connect_$1
        type: GAUGE
        labels:
          connector: "$2"
          task: "$3"
      - pattern: kafka.connect<type=(.+)><>Value
        name: kafka_connect_$1
        type: GAUGE
      - pattern: debezium.(.+)<type=connector-metrics, context=(.+), server=(.+)><>(\w+)
        name: debezium_metrics_$1_$4
        type: GAUGE
        labels:
          context: "$2"
          server: "$3"
